# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-dms-iam
  description: This component provisions IAM roles required for DMS
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







